version: "3.8"

networks:
  web:
    external: true

services:
  app:
    image: ghcr.io/gygmor/vierkorken-repo1:latest
    container_name: vierkorken-app
    restart: unless-stopped
    networks:
      - web
    environment:
      # ============================================================
      # APP CONFIGURATION
      # ============================================================
      NODE_ENV: "production"
      PORT: "3000"
      NEXT_PUBLIC_APP_URL: "http://192.168.20.10:8080"
      NEXT_PUBLIC_SITE_NAME: "VIERKORKEN"
      NEXT_PUBLIC_CURRENCY: "CHF"

      # ============================================================
      # DATABASE (MariaDB - VLAN 30) - ✅ FERTIG!
      # ============================================================
      DATABASE_URL: "mysql://vierkorken_app:FGDN8YEH1IiRei8@192.168.30.10:3306/vierkorken"

      # ============================================================
      # AUTHENTICATION (NextAuth.js) - ✅ FERTIG!
      # Secret wurde automatisch generiert: a6c9e17ed75401e1d98b0048d65153e30fc46f2ef4617aa92475e46e591aa400
      # ============================================================
      NEXTAUTH_URL: "http://192.168.20.10:8080"
      NEXTAUTH_SECRET: "a6c9e17ed75401e1d98b0048d65153e30fc46f2ef4617aa92475e46e591aa400"
      JWT_SECRET: "a6c9e17ed75401e1d98b0048d65153e30fc46f2ef4617aa92475e46e591aa400"

      # ============================================================
      # STRIPE PAYMENT (Zahlungen) - ✅ FERTIG!
      # Test Keys von deinem Stripe Account
      # ============================================================
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_YOUR_STRIPE_PUBLISHABLE_KEY"
      STRIPE_SECRET_KEY: "sk_test_YOUR_STRIPE_SECRET_KEY"
      STRIPE_WEBHOOK_SECRET: "whsec_YOUR_STRIPE_WEBHOOK_SECRET"

      # ============================================================
      # EMAIL via Microsoft Graph API (Modern & Secure) - ✅ FERTIG!
      # Verwendet OAuth2 statt SMTP - funktioniert mit Security Defaults
      # Siehe AZURE-APP-REGISTRATION.md für Setup-Anleitung
      # ============================================================
      MS_TENANT_ID: "YOUR_MS_TENANT_ID"
      MS_CLIENT_ID: "YOUR_MS_CLIENT_ID"
      MS_CLIENT_SECRET: "YOUR_MS_CLIENT_SECRET"
      MAIL_FROM_INFO: "info@vierkorken.ch"
      MAIL_FROM_NOREPLY: "no-reply@vierkorken.ch"
      ADMIN_EMAIL: "admin@vierkorken.ch"

      # ============================================================
      # KLARA INTEGRATION (Externe Produktdatenbank) - ✅ FERTIG!
      # API Keys von deinem alten PHP System übernommen
      # ============================================================
      KLARA_API_URL: "https://api.klara.ch"
      KLARA_API_KEY: "YOUR_KLARA_API_KEY"
      KLARA_API_SECRET: "YOUR_KLARA_API_SECRET"
      USE_MOCK_KLARA: "false"

      # ============================================================
      # MAINTENANCE MODE
      # ============================================================
      MAINTENANCE_MODE: "false"

      # ============================================================
      # OPTIONAL - Nicht konfiguriert (leer lassen)
      # ============================================================
      NEXI_API_KEY: ""
      NEXI_MERCHANT_ID: ""

    expose:
      - "3000"

    # Volumes für hochgeladene Bilder (persistent)
    volumes:
      - ./uploads:/app/public/uploads

    # Health Check (optional - für Monitoring)
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
